FROM mhart/alpine-node:latest AS builder
WORKDIR /src/c

COPY . .
RUN npm install
RUN npm run build

FROM mhart/alpine-node
RUN yarn global add serve
WORKDIR /src/client
COPY --from=builder /app/build .

EXPOSE 3000
CMD ["serve", "-p", "80", "-s", "."]
