-- MySQL Script generated by MySQL Workbench
-- Tue May 18 00:03:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema insurance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema insurance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insurance` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `insurance` ;

-- -----------------------------------------------------
-- Table `insurance`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`hospital` (
  `Hospital_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `IsNetworked` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Hospital_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`disease` (
  `code` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `hospital_id` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `disease_ibfk_1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `insurance`.`hospital` (`Hospital_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`billing` (
  `Bill_id` INT NOT NULL AUTO_INCREMENT,
  `disease_code` INT NOT NULL,
  `Bill_amout` FLOAT NULL DEFAULT NULL,
  `dateOfAdmission` DATE NULL DEFAULT NULL,
  `dateOfDischarge` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Bill_id`),
  INDEX `disease_code` (`disease_code` ASC) VISIBLE,
  CONSTRAINT `billing_ibfk_1`
    FOREIGN KEY (`disease_code`)
    REFERENCES `insurance`.`disease` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`policy` (
  `Policy_Number` INT NOT NULL AUTO_INCREMENT,
  `tenure` VARCHAR(50) NULL DEFAULT NULL,
  `policy_benefits` VARCHAR(50) NULL DEFAULT NULL,
  `Sum_insured` INT NULL DEFAULT NULL,
  `Policy_type` VARCHAR(50) NULL DEFAULT NULL,
  `Medical_History` VARCHAR(255) NULL DEFAULT NULL,
  `Premium` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Policy_Number`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`person` (
  `Person_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `phone_number` INT NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`claim` (
  `Claim_id` INT NOT NULL AUTO_INCREMENT,
  `Policy_number` INT NOT NULL,
  `person_id` INT NOT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `issued_date` DATE NULL DEFAULT NULL,
  `issued_amount` VARCHAR(50) NULL DEFAULT NULL,
  `start_date` VARCHAR(50) NULL DEFAULT NULL,
  `end_date` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Claim_id`),
  INDEX `Policy_number` (`Policy_number` ASC) VISIBLE,
  INDEX `person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `claim_ibfk_1`
    FOREIGN KEY (`Policy_number`)
    REFERENCES `insurance`.`policy` (`Policy_Number`),
  CONSTRAINT `claim_ibfk_2`
    FOREIGN KEY (`person_id`)
    REFERENCES `insurance`.`person` (`Person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`persondisease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`persondisease` (
  `person_id` INT NULL DEFAULT NULL,
  `disease_id` INT NULL DEFAULT NULL,
  INDEX `person_id` (`person_id` ASC) VISIBLE,
  INDEX `disease_id` (`disease_id` ASC) VISIBLE,
  CONSTRAINT `persondisease_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `insurance`.`person` (`Person_id`),
  CONSTRAINT `persondisease_ibfk_2`
    FOREIGN KEY (`disease_id`)
    REFERENCES `insurance`.`disease` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insurance`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance`.`test` (
  `code` INT NOT NULL AUTO_INCREMENT,
  `disease_code` INT NOT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `disease_code` (`disease_code` ASC) VISIBLE,
  CONSTRAINT `test_ibfk_1`
    FOREIGN KEY (`disease_code`)
    REFERENCES `insurance`.`disease` (`code`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
